version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: sceneplanner-postgres
        restart: always
        environment:
            POSTGRES_DB: sceneplanner
            POSTGRES_USER: dev_user
            POSTGRES_PASSWORD: qwerty
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
