name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: maven

            - name: Fetch dependencies
              run: mvn dependency:go-offline --batch-mode

            - name: Build & test
              run: mvn install

            - name: Check formatting
              run: mvn spotless:check
